tinyMCE.addI18n('en.tagwrap_dlg',{
	
    title : "Insert HTML5 Tags",
	titleA : "Insert A Tag",
	titleAbbr : "Insert ABBR Tag",
	titleArea : "Insert AREA Tag",
	titleAside : "Insert ASIDE Tag",
	titleAudio : "Insert AUDIO Tag",
	titleBase : "Insert BASE Tag",
	titleBdo : "Insert BDO Tag",
	titleBody : "Insert BODY Tag",
	titleBr : "Insert BR Tag",
	titleButton : "Insert BUTTON Tag",
	titleCanvas : "Insert CANVAS Tag",
	titleCite : "Insert CITE Tag",
	titleCol : "Insert COL Tag",
	titleColgroup : "Insert COLGROUP Tag",
	titleData : "Insert DATA Tag",
	titleDatalist : "Insert DATALIST Tag",
	titleDiv : "Insert DIV Tag",
	titleEmbed : "Insert EMBED Tag",
	titleEventsource : "Insert EVENTSOURCE Tag",
	titleFieldset : "Insert FIELDSET Tag",
	titleFigure : "Insert FIGURE Tag",
	titleForm : "Insert FORM Tag",
	titleH1 : "Insert H1 Tag",
	titleH2 : "Insert H2 Tag",
	titleH3 : "Insert H3 Tag",
	titleH4 : "Insert H4 Tag",
	titleH5 : "Insert H5 Tag",
	titleH6 : "Insert H6 Tag",
	titleHr : "Insert HR Tag",
	titleIframe : "Insert IFRAME Tag",
	titleImg : "Insert IMG Tag",
	titleInput : "Insert INPUT Tag",
	titleLabel : "Insert LABEL Tag",
	titleLi : "Insert LI Tag",
	titleLink : "Insert LINK Tag",
	titleMark : "Insert MARK Tag",
	titleMap : "Insert MAP Tag",
	titleMeta : "Insert META Tag",
	titleMeter : "Insert METER Tag",
	titleNav : "Insert NAV Tag",
	titleObject : "Insert OBJECT Tag",
	titleOl : "Insert OL Tag",
	titleOptgroup : "Insert OPTGROUP Tag",
	titleOption : "Insert OPTION Tag",
	titleOutput : "Insert OUTPUT Tag",
	titleP : "Insert P Tag",
	titleParam : "Insert PARAM Tag",
	titlePre : "Insert PRE Tag",
	titleProgress : "Insert PROGRESS Tag",
	titleScript : "Insert SCRIPT Tag",
	titleSelect : "Insert SELECT Tag",
	titleSource : "Insert SOURCE Tag",
	titleSpan : "Insert SPAN Tag",
	titleStyle : "Insert STYLE Tag",
	titleTable : "Insert TABLE Tag",
	titleTd : "Insert TD Tag",
	titleTextarea : "Insert TEXTAREA Tag",
	titleTh : "Insert TH Tag",
	titleTr : "Insert TR Tag",
	titleTrack : "Insert TRACK Tag",
	titleUl : "Insert UL Tag",
	titleVideo : "Insert VIDEO Tag",
	
	
    instr : "Choose the desired HTML tags:",
	
	
	note : "Below is a complete list of HTML tags from the HTML 5 specification. The HTML tags are listed alphabetically to help you quickly find the tag you're looking for (or to find out whether it exists or not!). Hover over each tag for a brief description.",
	
	
	noteA : 'You have selected the <strong>a</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteAbbr : 'You have selected the <strong>abbr</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteArea : 'You have selected the <strong>area</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteAside : 'You have selected the <strong>aside</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteAudio : 'You have selected the <strong>audio</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteBase : 'You have selected the <strong>base</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteBdo : 'You have selected the <strong>bdo</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteBody : 'You have selected the <strong>body</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteBr : 'You have selected the <strong>br</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteButton : 'You have selected the <strong>button</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteCanvas : 'You have selected the <strong>canvas</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteCite : 'You have selected the <strong>cite</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteCol : 'You have selected the <strong>col</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteColgroup : 'You have selected the <strong>colgroup</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteData : 'You have selected the <strong>data</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteDatalist : 'You have selected the <strong>datalist</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteDiv : 'You have selected the <strong>div</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteEmbed : 'You have selected the <strong>embed</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteEventsource : 'You have selected the <strong>eventsource</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteFieldset : 'You have selected the <strong>fieldset</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteFigure : 'You have selected the <strong>figure</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteForm : 'You have selected the <strong>form</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteH1 : 'You have selected the <strong>h1</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteH2 : 'You have selected the <strong>h2</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteH3 : 'You have selected the <strong>h3</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteH4 : 'You have selected the <strong>h4</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteH5 : 'You have selected the <strong>h5</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteH6 : 'You have selected the <strong>h6</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteHr : 'You have selected the <strong>hr</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteIframe : 'You have selected the <strong>iframe</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteImg : 'You have selected the <strong>img</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteInput : 'You have selected the <strong>input</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteLabel : 'You have selected the <strong>label</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteLi : 'You have selected the <strong>li</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteLink : 'You have selected the <strong>link</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteMark : 'You have selected the <strong>mark</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteMap : 'You have selected the <strong>map</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteMeta : 'You have selected the <strong>meta</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteMeter : 'You have selected the <strong>meter</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteNav : 'You have selected the <strong>nav</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteObject : 'You have selected the <strong>object</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteOl : 'You have selected the <strong>ol</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteOptgroup : 'You have selected the <strong>optgroup</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteOption : 'You have selected the <strong>option</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteOutput : 'You have selected the <strong>output</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteP : 'You have selected the <strong>p</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteParam : 'You have selected the <strong>param</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	notePre : 'You have selected the <strong>pre</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteProgress : 'You have selected the <strong>progress</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteScript : 'You have selected the <strong>script</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteSelect : 'You have selected the <strong>select</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteSource : 'You have selected the <strong>source</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteSpan : 'You have selected the <strong>span</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteStyle : 'You have selected the <strong>style</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteTable : 'You have selected the <strong>table</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteTd : 'You have selected the <strong>td</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteTextarea : 'You have selected the <strong>textarea</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteTh : 'You have selected the <strong>th</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteTr : 'You have selected the <strong>tr</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteTrack : 'You have selected the <strong>track</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteUl : 'You have selected the <strong>ul</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	noteVideo : 'You have selected the <strong>video</strong> tag. Your tag may be refined using the options below.<br />Click "Insert" to insert selection.<br /><br /><br />',
	
	
	noteA1 : "Enter HREF Address:",
	noteA2 : "Select Target Window:",
	noteA3 : "The HTML <strong>&#60;a&#62;</strong> tag is used for creating a hyperlink to another web page.<br /><br />You can use the <strong><em>target</em></strong> attribute to specify whether to open the web page in a new browser window or not.<br /><br />You can also use this tag to link an image.<br /><br /><br />",
	
	noteAbbr1 : "Enter Title Attribute:",
	noteAbbr2 : "The HTML <strong>&#60;abbr&#62;</strong> tag is used for indicating an abbreviation.<br /><br />This tag is often used in conjunction with the global title attribute in order to provide an expansion of the abbreviation. When this attribute is specified, it should only contain an expansion of the abbreviation and nothing else.<br /><br /><br />",
	
	noteArea1 : "Enter Area Alternate Text:",
	noteArea2 : "Select Shape:",
	noteArea3 : "The HTML <strong>&#60;area&#62;</strong> tag is used for defining an area in an image map. Image maps are images with clickable areas (sometimes referred to as 'hotspots') that usually link to another page. <br /><br />Note that this tag is always nested within the <strong>&#60;map&#62;</strong> tag.<br /><br /><br />",
	
	noteAside1 : "Enter CSS Styling:",
	noteAside2 : "The HTML <strong>&#60;aside&#62;</strong> tag is used to represent content that is related to the surrounding content within an article or web page, but could still stand alone in its own right. This type of content is often represented in sidebars.<br /><br />An example is a 'pull quote' from a longer article. A pull quote (also known as a lift-out quote or a call-out) is a quotation or edited excerpt from an article that is placed in a larger typeface on the same page, serving to lead readers into an article and to highlight a key topic.<br /><br /><br />",
	
	noteAudio1 : "Enter Audio Source:",
	noteAudio2 : "(Required)",
	noteAudio3 : "The HTML <strong>&#60;audio&#62;</strong> tag is used to specify audio on an HTML document.<br /><br />For example, you could embed a music file on your web page for your visitors to listen to.<br /><br /><br />",
	
	noteBase1 : "Enter Base HREF Address:",
	noteBase2 : "Select Base Target Window:",
	noteBase3 : "The HTML <strong>&#60;base&#62;</strong> tag is used to specify a base URI, or URL, for relative links. For example, you can set the base URL once at the top of your page, then all subsequent relative links will use that URL as a starting point.<br /><br />The <strong>&#60;base&#62;</strong> tag must be between the document's <strong>&#60;head&#62;</strong> tags. Also, there must be no more than one base element per document.<br /><br /><br />",
	
	noteBdo1 : "Set Text Direction:",
	noteBdo2 : "The HTML <strong>&#60;bdo&#62;</strong> tag is used for overriding the text direction.<br /><br />This can be useful when displaying right-to-left written text (such as Hebrew, Arabic, and other languages/scripts that are written from right to left) within left-to-right text (such as English) or vice versa.<br /><br /><br />",
	
	noteBody1 : "Enter Style Attributes:",
	noteBody2 : "(Optional)",
	noteBody3 : "The HTML <strong>&#60;body&#62;</strong> tag is used for indicating the main content section of the HTML document.<br /><br />The body tag is placed between the <strong>&#60;/head&#62;</strong> and the <strong>&#60;/html&#62;</strong> tags.<br /><br /><br />",
	
	noteBr1 : "Enter Style Attributes:",
	noteBr2 : "(Optional)",
	noteBr3 : "The HTML <strong>&#60;br&#62;</strong> tag is used for specifying a line break.<br /><br />The <strong>&#60;br&#62;</strong> tag is an empty tag. In other words, it has no end tag.<br /><br /><br />",
	
	noteButton1 : "Enter Button Name:",
	noteButton2 : "Enter Button Value:",
	noteButton3 : "Enter Button ID:",
	noteButton4 : "Enter Button Class:",
	noteButton5 : "Select Button Type:",
	noteButton6 : "Enter Button Form ID:",
	noteButton7 : "(Assigns the name of the control.)",
	noteButton8 : "(Assigns an initial value to the control. This attribute must only be present if the form attribute is present.)",
	noteButton9 : "(ID to apply stlyes to button.)",
	noteButton10 : "(Class to apply styles to button.)",
	noteButton11 : "(Specifies the type of button.)",
	noteButton12 : "(Specifies the ID of a form to which this control belongs.)",
	noteButton13 : "The HTML <strong>&#60;button&#62;</strong> tag is used for creating a button control.<br /><br />Although this tag is often used in conjunction with the <strong>&#60;form&#62;</strong> tag, it can also be used as a standalone control.<br /><br /><br />",
	
	noteCanvas1 : "Enter Camvas ID:",
	noteCanvas2 : "Enter Canvas Width:",
	noteCanvas3 : "Enter Canvas Height:",
	noteCanvas4 : "The HTML <strong>&#60;canvas&#62;</strong> tag is used for creating graphics on the fly. It can be used for rendering graphs, game graphics, or other visual images.<br /><br />To draw on the canvas, the <strong>&#60;canvas&#62;</strong> tag is used in conjunction with the <strong><em>getContext(contextId)</em></strong> method.<br /><br />Any content between the <strong>&#60;canvas&#62;</strong><strong>&#60;/canvas&#62;</strong> tags is 'fallback content'- meaning, it will be displayed only if the canvas cannot be displayed.<br /><br />The <strong>&#60;canvas&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteCite1 : "Enter Title Attribute:",
	noteCite2 : "The HTML <strong>&#60;cite&#62;</strong> tag is used for indicating a citation.<br /><br />Text enclosed in <strong>&#60;cite&#62;</strong> tags is intended to represent the title of a work (e.g. a book, a paper, an essay, a poem, a score, a song, a script, a film, a TV show, a game, a sculpture, a painting, a theatre production, a play, an opera, a musical, an exhibition, etc).<br /><br /><br />",
	
	noteCol1 : "Enter Column Width:",
	noteCol2 : "The HTML <strong>&#60;col&#62;</strong> tag is used for specifying column properties for each column within a colgroup.<br /><br />You would normally only use this tag if the values for each column is different. Otherwise, you can specify the properties as part of the colgroup tag.<br /><br />Must be used within a HTML <strong><em>colgroup</em></strong> element that doesn't have a <strong><em>span</em></strong> attribute.<br /><br /><br />",
	
	noteColgroup1 : "Enter Column Group Span:",
	noteColgroup2 : "Enter Column Group Style Attributes:",
	noteColgroup3 : "(Must be a postive integer)",
	noteColgroup4 : "(Optional)",
	noteColgroup5 : "The HTML <strong>&#60;colgroup&#62;</strong> tag is used for specifying properties for a group of columns within a table.<br /><br />Must be used as a child of a <strong>&#60;table&#62;</strong> element, after any <strong>&#60;caption&#62;</strong> elements and before any <strong>&#60;thead&#62;</strong>, <strong>&#60;tbody&#62;</strong>, <strong>&#60;tfoot&#62;</strong>, and <strong>&#60;tr&#62;</strong> elements.<br /><br /><br />",
	
	noteData1 : "Enter Data Value:",
	noteData2 : "The HTML <strong>&#60;data&#62;</strong> tag is used for providing a machine-readable version of its own contents. This can be useful in cases where your data needs to be in a certain format because it may be processed by a script, but this might not be the format that you'd like your users to see.<br /><br />For example, you might prefer to present numbers to your users written with letters (eg, One, Two, Three... etc), but you might also have a script that sorts the numbers in ascending or descending order. Such a script may require that the numbers are provided as numbers (eg, 1, 2, 3... etc) instead. The <strong>&#60;data&#62;</strong> tag enables you to overcome this by providing two numbers - one for the users (provided within the <strong>&#60;data&#62;</strong><strong>&#60;/data&#62;</strong> tags) and one for the script (provided in the value attribute). This could look something like: <strong>&#60;data value='1'&#62;One&#60;/data&#62;</strong><br /><br />Note that if the value is date or time related, use the <strong>&#60;time&#62;</strong> tag instead.<br /><br /><br />",
	
	noteDatalist1 : "Enter Datalist ID:",
	noteDatalist2 : "The HTML <strong>&#60;datalist&#62;</strong> tag is used for providing an 'autocomplete' feature on form elements. It enables you to provide a list of predefined options to the user as they input data.<br /><br />For example, if a user began entering some text into a text field, a list would drop down with prefilled values that they could choose from.<br /><br /><br />",
	
	noteDiv1 : "Enter Style Attributes:",
	noteDiv2 : "(optional)",
	noteDiv3 : "The HTML <strong>&#60;div&#62;</strong> tag is used for defining a section of your document. With the <strong>&#60;div&#62;</strong> tag, you can group large sections of HTML elements together and format them with CSS.<br /><br />The difference between the <strong>&#60;div&#62;</strong> tag and the <strong>&#60;span&#62;</strong> tag is that the <strong>&#60;div&#62;</strong> tag is used with block-level elements whilst the <strong>&#60;span&#62;</strong> tag is used with inline elements.<br /><br /><br />",
	
	noteEmbed1 : "Enter Embed Source:",
	noteEmbed2 : "Enter Embed Type:",
	noteEmbed3 : "Enter Embed Width:",
	noteEmbed4 : "Enter Embed Height:",
	noteEmbed5 : "The HTML <strong>&#60;embed&#62;</strong> tag is used for embedding an external application or interactive content into an HTML document.<br /><br />Note that the <strong>&#60;embed&#62;</strong> element is an empty element (no closing tag is used).<br /><br />The <strong>&#60;embed&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteEventsource1 : "Enter Eventsource Source URL:",
	noteEventsource2 : "(Must be a URL that uses the text/event-stream format.)",
	noteEventsource3 : "The HTML <strong>&#60;eventsource&#62;</strong> tag represents a target for events generated by a remote server.<br /><br />Note that the <strong>&#60;eventsource&#62;</strong> element is an empty element (no closing tag is used).<br /><br />The <strong>&#60;eventsource&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteFieldset1 : "Enter Fieldset Name:",
	noteFieldset2 : "Enter Fieldset Form:",
	noteFieldset3 : "(Specifies the name of the fieldset.)",
	noteFieldset4 : "(Specifies a form to associate this fieldset element with. The value must be a ID of a form element.)",
	noteFieldset5 : "The HTML <strong>&#60;fieldset&#62;</strong> tag is used for grouping related form elements.<br /><br />By using the fieldset tag and the <strong>&#60;legend&#62;</strong> tag, you can make your forms much easier to understand for your users. You can also do things like, disable all child elements within a <strong>&#60;fieldset&#62;</strong>.<br /><br /><br />",
	
	noteFigure1 : "Enter Figure ID:",
	noteFigure2 : "(Only numeric number, no pound sign)",
	noteFigure3 : "The HTML <strong>&#60;figure&#62;</strong> tag is used for annotating illustrations, diagrams, photos, code listings, etc.<br /><br />You can use the <strong>&#60;figure&#62;</strong> element to associate a caption together with some embedded content, such as a graphic or video.<br /><br />You can use the <strong>&#60;figure&#62;</strong> element in conjunction with the <strong>&#60;figcaption&#62;</strong> element to provide a caption for the contents of your <strong>&#60;figure&#62;</strong> element.<br /><br />The <strong>&#60;figure&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteForm1 : "Enter Form Action URL:",
	noteForm2 : "Choose Form Autocomplete:",
	noteForm3 : "Select Form Encryption Type:",
	noteForm4 : "Select Form Method:",
	noteForm5 : "Enter Form Name:",
	noteForm6 : "Select Form Target:",
	noteForm7 : "(Specifies a URI/URL of the page that will process the form.)",
	noteForm8 : "(Specifies whether the form fields should be automatically completed based on the user's history.)",
	noteForm9 : "(Specifies the content type used to encode the form data set when it's submitted to the server.)",
	noteForm10 : "(Specifies the HTTP method to use when the form is submitted.)",
	noteForm11 : "(Assigns a name to the form. This is used when referencing the form with stylesheets or scripts.)",
	noteForm12 : "(Used for http response message headers. For example http-equiv can be used to periodically refresh the page, redirect to another page, etc.)",
	noteForm13 : "The HTML <strong>&#60;form&#62;</strong> tag is used for declaring a form.<br /><br />The <strong>&#60;form&#62;</strong> tag is used in conjunction with form-associated elements. To create a form, you can nest form-associated elements inside the opening/closing <strong>&#60;form&#62;</strong> tags. You can also use the form attribute within those elements to reference the ID of the form to use.<br /><br /><br />",
	
	noteH11 : "Enter Style Attributes:",
	noteH12 : "(Optional)",
	noteH13 : "The HTML <strong>&#60;h1&#62;</strong> tag is used for specifying level 1 headings.<br /><br />In HTML, there are 6 levels of headings (<strong>&#60;h1&#62;</strong> - <strong>&#60;h6&#62;</strong>) with <strong>&#60;h1&#62;</strong> the most important and <strong>&#60;h6&#62;</strong> the least important.<br /><br />Browsers typically render the various headings in different sizes - with <strong>&#60;h1&#62;</strong> being the largest and <strong>&#60;h6&#62;</strong> being the smallest.<br /><br /><br />",
	
	noteH21 : "Enter Style Attributes:",
	noteH22 : "(Optional)",
	noteH23 : "The HTML <strong>&#60;h2&#62;</strong> tag is used for specifying level 2 headings.<br /><br />In HTML, there are 6 levels of headings (<strong>&#60;h1&#62;</strong> - <strong>&#60;h6&#62;</strong>) with <strong>&#60;h1&#62;</strong> the most important and <strong>&#60;h6&#62;</strong> the least important.<br /><br />Browsers typically render the various headings in different sizes - with <strong>&#60;h1&#62;</strong> being the largest and <strong>&#60;h6&#62;</strong> being the smallest.<br /><br /><br />",
	
	noteH31 : "Enter Style Attributes:",
	noteH32 : "(Optional)",
	noteH33 : "The HTML <strong>&#60;h3&#62;</strong> tag is used for specifying level 3 headings.<br /><br />In HTML, there are 6 levels of headings (<strong>&#60;h1&#62;</strong> - <strong>&#60;h6&#62;</strong>) with <strong>&#60;h1&#62;</strong> the most important and <strong>&#60;h6&#62;</strong> the least important.<br /><br />Browsers typically render the various headings in different sizes - with <strong>&#60;h1&#62;</strong> being the largest and <strong>&#60;h6&#62;</strong> being the smallest.<br /><br /><br />",
	
	noteH41 : "Enter Style Attributes:",
	noteH42 : "(Optional)",
	noteH43 : "The HTML <strong>&#60;h4&#62;</strong> tag is used for specifying level 4 headings.<br /><br />In HTML, there are 6 levels of headings (<strong>&#60;h1&#62;</strong> - <strong>&#60;h6&#62;</strong>) with <strong>&#60;h1&#62;</strong> the most important and <strong>&#60;h6&#62;</strong> the least important.<br /><br />Browsers typically render the various headings in different sizes - with <strong>&#60;h1&#62;</strong> being the largest and <strong>&#60;h6&#62;</strong> being the smallest.<br /><br /><br />",
	
	noteH51 : "Enter Style Attributes:",
	noteH52 : "(Optional)",
	noteH53 : "The HTML <strong>&#60;h5&#62;</strong> tag is used for specifying level 5 headings.<br /><br />In HTML, there are 6 levels of headings (<strong>&#60;h1&#62;</strong> - <strong>&#60;h6&#62;</strong>) with <strong>&#60;h1&#62;</strong> the most important and <strong>&#60;h6&#62;</strong> the least important.<br /><br />Browsers typically render the various headings in different sizes - with <strong>&#60;h1&#62;</strong> being the largest and <strong>&#60;h6&#62;</strong> being the smallest.<br /><br /><br />",
	
	noteH61 : "Enter Style Attributes:",
	noteH62 : "(Optional)",
	noteH63 : "The HTML <strong>&#60;h6&#62;</strong> tag is used for specifying level 6 headings.<br /><br />In HTML, there are 6 levels of headings (<strong>&#60;h1&#62;</strong> - <strong>&#60;h6&#62;</strong>) with <strong>&#60;h1&#62;</strong> the most important and <strong>&#60;h6&#62;</strong> the least important.<br /><br />Browsers typically render the various headings in different sizes - with <strong>&#60;h1&#62;</strong> being the largest and <strong>&#60;h6&#62;</strong> being the smallest.<br /><br /><br />",
	
	noteHr1 : "Enter Style Attributes:",
	noteHr2 : "(optional)",
	noteHr3 : "The HTML <strong>&#60;hr&#62;</strong> tag is used for specifying a horizontal rule in an HTML document.<br /><br />The intention behind the <strong>&#60;hr&#62;</strong> tag is that it indicates a paragraph-level thematic break. For example, a scene change in a story, or a transition to another topic within a section of a reference book.<br /><br /><br />",
	
	noteIframe1 : "Enter iFrame Url:",
	noteIframe2 : "Enter iFrame Width:",
	noteIframe3 : "Enter iFrame Height:",
	noteIframe4 : "Enter iFrame Name:",
	noteIframe5 : "(Location of the frame contents (for example, the HTML page to be loaded into the frame).)",
	noteIframe6 : "(Specifies the width of the inline frame.)",
	noteIframe7 : "(Specifies the height of the inline frame.)",
	noteIframe8 : "(Assigns a name to a frame. This is useful for loading contents into one frame from another.)",
	noteIframe9 : "The HTML <strong>&#60;iframe&#62;</strong> tag is used to specify an inline frame.<br /><br />An inline frame allows you to embed another document within the current HTML document. The HTML 5 specification refers to this as a 'nested browsing context'.<br /><br /><br />",
	
	noteImg1 : "Enter Image Source:",
	noteImg2 : "Enter Image Title Description:",
	noteImg3 : "Enter Image Alternate Description:",
	noteImg4 : "Enter Image Width:",
	noteImg5 : "Enter Image Height:",
	noteImg6 : "Enter Image UseMap ID:",
	noteImg7 : "Enter List Item Style Attributes:",
	noteImg8 : "(Optional)",
	noteImg9 : "The HTML <strong>&#60;img&#62;</strong> tag is used for embedding images into an HTML document.<br /><br />The value given by the <strong><em>src</em></strong> attribute is the URL to the embedded image. The value of the <strong><em>alt</em></strong> attribute appears if the image cannot be loaded.<br /><br />To link an image to another document, you simply nest the <strong>&#60;img&#62;</strong> tag inside <strong>&#60;a&#62;</strong> tags.<br /><br /><br />",
	
	noteInput1 : "Choose Input Type:",
	noteInput2 : "Enter Input Name:",
	noteInput3 : "Enter Input Value:",
	noteInput4 : "Enter Input Alternate Description:",
	noteInput5 : "Enter Input Width:",
	noteInput6 : "Enter Input Height:",
	noteInput7 : "Enter Input Placeholder:",
	noteInput8 : "(Specifies the type of control.)",
	noteInput9 : "(Assigns a name to the input control.)",
	noteInput10 : "(Specifies a default value for the control. Note: If type='checkbox' or type='radio' this attribute is required.)",
	noteInput11 : "(This specifies text to be used in case the browser/user agent can't render the input control.)",
	noteInput12 : "(Specifies the width of the control.)",
	noteInput13 : "(Specifies the height of the control.)",
	noteInput14 : "(Specifies a short hint (a word or short phrase) intended to aid the user with data entry.)",
	noteInput15 : "The HTML <strong>&#60;input&#62;</strong> tag is used within a form to declare an input element - a control that allows the user to input data.<br /><br /><br />",
	
	noteLabel1 : "Enter Style Attributes:",
	noteLabel2 : "Enter Label Form ID:",
	noteLabel3 : "(Specifies the input control that this label is for. This value must match the input control's 'id' attribute.)",
	noteLabel4 : "(Specifies the ID of a form to which this control belongs.)",
	noteLabel5 : "The HTML <strong>&#60;label&#62;</strong> tag is used for adding a label to a form control. It can also be used on <strong>&#60;meter&#62;</strong> and <strong>&#60;progress&#62;</strong> elements, as well as the <strong>&#60;output&#62;</strong> element.<br /><br />If you use the <strong>&#60;label&#62;</strong> tag, in some browsers, users can select a radio button or checkbox option by clicking on its label.<br /><br /><br />",
	
	noteLi1 : "Enter List Item Value:",
	noteLi2 : "Enter List Item Style Attributes:",
	noteLi3 : "(Optional)",
	noteLi4 : "(Optional)",
	noteLi5 : "The HTML <strong>&#60;li&#62;</strong> tag is used for specifying a list item in ordered, unordered, directory, and menu lists.<br /><br />This element can be used in conjunction with the <strong>&#60;ol&#62;</strong>, <strong>&#60;ul&#62;</strong>, and <strong>&#60;menu&#62;</strong> elements.<br /><br /><br />",
	
	noteLink1 : "Enter Base HREF Address:",
	noteLink2 : "Select Relative Value:",
	noteLink3 : "The HTML <strong>&#60;link&#62;</strong> tag is used for defining a link to an external document. It is placed in in the <strong>&#60;head&#62;</strong> section of the document.<br /><br />The <strong>&#60;link&#62;</strong> tag is commonly used for linking to an external style sheet.<br /><br />Despite its name ('link'), the link tag is <strong>not</strong> used for creating a hyperlink to another HTML document. If you need to link to another HTML document, use the HTML <strong>&#60;a&#62;</strong> tag.<br /><br /><br />",
	
	noteMap1 : "Enter Map ID:",
	noteMap2 : "Enter Map Name:",
	noteMap3 : "The HTML <strong>&#60;map&#62;</strong> tag is used for declaring an image map.<br /><br />The <strong>&#60;map&#62;</strong> tag is used in conjunction with the <strong>&#60;area&#62;</strong> tag and <strong>&#60;img&#62;</strong> tag to specify clickable areas (sometimes referred to as 'hot spots') on an image.<br /><br />To create an image map, you use the <strong>&#60;map&#62;</strong> tag to declare the image map, and the <strong>&#60;area&#62;</strong> tag (nested within the <strong>&#60;map&#62;</strong> tag) to define the clickable areas. The <strong>&#60;img&#62;</strong> tag can be defined elsewhere on the page, and is linked to the <strong>&#60;map&#62;</strong> element using the ID attribute.<br /><br /><br />",
	
	noteMark1 : "Enter Style Attributes:",
	noteMark2 : "(Optional)",
	noteMark3 : "The HTML <strong>&#60;mark&#62;</strong> tag is used for indicating text as marked or highlighted for reference purposes, due to its relevance in another context.<br /><br />The <strong>&#60;mark&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteMeta1 : "Enter Meta Name:",
	noteMeta2 : "Enter Meta Content:",
	noteMeta3 : "Enter Meta Character Set:",
	noteMeta4 : "Enter Meta http-equiv:",
	noteMeta5 : "(Name for the property.)",
	noteMeta6 : "(Specifies the property's value.)",
	noteMeta7 : "(Specifies the character encoding used by the document.)",
	noteMeta8 : "(Used for http response message headers. For example http-equiv can be used to periodically refresh the page, redirect to another page, etc.)",
	noteMeta9 : "The HTML <strong>&#60;meta&#62;</strong> tag is used for declaring metadata for the HTML document.<br /><br />Metadata can include document decription, keywords, author etc. It can also be used to refresh the page or set cookies.<br /><br />The meta tag is placed between the opening/closing <strong>&#60;head&#62;</strong> <strong>&#60;/head&#62;</strong> tags.<br /><br /><br />",
	
	noteMeter1 : "Enter Title:",
	noteMeter2 : "Enter Value:",
	noteMeter3 : "Enter Minimum:",
	noteMeter4 : "Enter Low:",
	noteMeter5 : "Enter High:",
	noteMeter6 : "Enter Max:",
	noteMeter7 : "Enter Optimum:",
	noteMeter8 : "(Specifies the title.)",
	noteMeter9 : "(Specifies the 'measured' value.)",
	noteMeter10 : "(Specifies the lower bound of the range. Default is 0.)",
	noteMeter11 : "(Specifies the range that is considered to be a 'low' value.)",
	noteMeter12 : "(Specifies the range that is considered to be a 'high' value.)",
	noteMeter13 : "(Specifies the upper bound of the range. Default is 1.)",
	noteMeter14 : "(Specifies the value that is considered to be the 'optimum', or best, value. If this value is higher than the 'high' value then it indicates that the higher the value, the better. If it's lower than the 'low' mark then it indicates that lower values are better. If it is in between then it indicates that neither high nor low values are good.)",
	noteMeter15 : "The HTML <strong>&#60;meter&#62;</strong> tag is used for indicating a scalar measurement within a known range, or a fractional value.<br /><br />Also known as a <em>gauge</em>, usage could include displaying disk usage, the amount raised during fundraising activities, or the relevance of a search query result.<br /><br />It is important to note that the <strong>&#60;meter&#62;</strong> element is used to represent a <em>range</em>. It is not appropriate to use this element for representing a single number (such as how many children someone has) unless there is a known maximum number.<br /><br />The <strong>&#60;meter&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteNav1 : "Enter Style Attributes:",
	noteNav2 : "(Optional)",
	noteNav3 : "The HTML <strong>&#60;nav&#62;</strong> tag is used for declaring a navigational section of the HTML document.<br /><br />Websites typically have sections dedicated to navigational links - links that enable the user to navigate the site. These links should be placed inside a <strong>&#60;nav&#62;</strong> tag.<br /><br />Note that links in the footer section should be marked up inside <strong>&#60;footer&#62;</strong> tags as opposed to <strong>&#60;nav&#62;</strong> tags.<br /><br />The <strong>&#60;nav&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteObject1 : "Enter Object Data Url:",
	noteObject2 : "Enter Object Type:",
	noteObject3 : "Enter Object Name:",
	noteObject4 : "Enter Object Width:",
	noteObject5 : "Enter Object Height:",
	noteObject6 : "Enter Enter Object Form ID:",
	noteObject7 : "Enter Object UseMap (if applicable):",
	noteObject8 : "(Specifies the location of data to be used by the object. The value must be a valid URL.)",
	noteObject9 : "(Specifies the object type as specified in the data attribute. Must be a valid MIME type.)",
	noteObject10 : "(Assigns the name of the object.)",
	noteObject11 : "(Specifies the width, in pixels, to display the external content.)",
	noteObject12 : "(Specifies the height, in pixels, to display the external content.)",
	noteObject13 : "(Specifies the ID of a form to which this object belongs.)",
	noteObject14 : "(Specifies the name of an image map to use on this object.)",
	noteObject15 : "The HTML <strong>&#60;object&#62;</strong> tag is used for embedding an object within an HTML document. Use this tag to embed multimedia in your web pages.<br /><br />You can use the <strong>&#60;param&#62;</strong> tag to pass parameters to plugins that have been embedded using the <strong>&#60;object&#62;</strong> tag.<br /><br />You can also use the <strong>&#60;object&#62;</strong> tag to embed another webpage into your HTML document.<br /><br /><br />",
	
	noteOl1 : "Enter List Start Number:",
	noteOl2 : "Select List Number Type:",
	noteOl3 : "The HTML <strong>&#60;ol&#62;</strong> tag is used for specifying an ordered list.<br /><br />Ordered lists are often numbered (1. 2. 3... etc), however, they don't necessarily have to be. The main point of an ordered list is that the list items have been ordered, such that changing the order would change the meaning of the list (or document).<br /><br />A list of instructions is a good candidate for an ordered list, with each list item representing a different step. Each step would need to be completed before the next step is started.<br /><br />This element is used in conjunction with the <strong>&#60;li&#62;</strong> element. The <strong>&#60;ol&#62;</strong> tag declares the ordered list, and the <strong>&#60;li&#62;</strong> tag declares each list item.<br /><br />You can also use the CSS <strong><em>list-style-type</em></strong> property to change the numbering system. For example, you could use roman numerals instead of decimal.<br /><br /><br />",
	
	noteOptgroup1 : "Enter Option Group Label:",
	noteOptgroup2 : "(Required)",
	noteOptgroup3 : "The HTML <strong>&#60;optgroup&#62;</strong> tag is used for grouping related options within your select list. This makes it easier for users to comprehend the options when looking at a large list.<br /><br /><br />",
	
	noteOption1 : "Enter Option Label:",
	noteOption2 : "Enter Option Value:",
	noteOption3 : "Enter Option Name:",
	noteOption4 : "(Optional)",
	noteOption5 : "(Optional)",
	noteOption6 : "(Optional)",
	noteOption7 : "The HTML <strong>&#60;option&#62;</strong> tag is used for defining option items within a list.<br /><br />This element can be used in conjunction with the <strong>&#60;select&#62;</strong> or <strong>&#60;datalist&#62;</strong> elements.<br /><br /><br />",
	
	noteOutput1 : "Enter Output For:",
	noteOutput2 : "Enter Output Form Reference:",
	noteOutput3 : "Enter Output Name:",
	noteOutput4 : "(The value must be one or more IDs (separated by a space) of elements within the same document.)",
	noteOutput5 : "(Associates the output with a form.)",
	noteOutput6 : "(Specifies the name of this element.)",
	noteOutput7 : "The HTML <strong>&#60;output&#62;</strong> tag is used for representing the result of a calculation, such as one performed by a script.<br /><br />The <strong>&#60;output&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteP1 : "Enter Style Attributes:",
	noteP2 : "(Optional)",
	noteP3 : "The HTML <strong>&#60;p&#62;</strong> tag is used for defining a paragraph.<br /><br />In certain situations, the <p> tag is not the best tag to use. It's a good idea to become familiar with other HTML tags that have a more specific purpose. Examples include <strong>&#60;footer&#62;</strong>, <strong>&#60;address&#62;</strong> and <strong>&#60;blockquote&#62;</strong> to name a few.<br /><br /><br />",
	
	noteParam1 : "Enter Name Attribute:",
	noteParam2 : "Enter Value Attribute:",
	noteParam3 : "(Required)",
	noteParam4 : "(Required)",
	noteParam5 : "The HTML <strong>&#60;param&#62;</strong> tag is used for passing parameters to an embedded object.<br /><br />This tag is used in conjunction with the <strong>&#60;object&#62;</strong> tag.<br /><br />To use the <strong>&#60;param&#62;</strong> tag, you need to nest it inside a <strong>&#60;object&#62;</strong> element.<br /><br /><br />",
	
	notePre1 : "Enter Style Attributes:",
	notePre2 : "(Optional)",
	notePre3 : "The HTML <strong>&#60;pra&#62;</strong> tag is used for indicating preformatted text. The code tag surrounds the code being marked up.<br /><br />Browsers normally render <strong>&#60;pra&#62;</strong> text in a fixed-pitched font, with whitespace in tact, and without word wrap.<br /><br /><br />",
	
	noteProgress1 : "Enter Progress Value:",
	noteProgress2 : "Enter Progress Max:",
	noteProgress3 : "(Required)",
	noteProgress4 : "(Required)",
	noteProgress5 : "The HTML <strong>&#60;progress&#62;</strong> tag is used for representing the progress of a task.<br /><br />This element could be used in conjunction with JavaScript to display the progress of a task or process as it is underway.<br /><br />The <strong>&#60;progress&#62;</strong> tag was introduced in HTML 5.<br /><br /><strong>Tip:</strong> The <strong>&#60;progress&#62;</strong> is not suitable for representing a gauge (such as disk space usage or a tally of votes). To represent a gauge, use the <strong>&#60;meter&#62;</strong> tag instead.<br /><br /><br />",
	
	noteScript1 : "Enter Script Source:",
	noteScript2 : "Enter Script Type:",
	noteScript3 : "Enter Script Character Set:",
	noteScript4 : "(Specifies a URI/URL of an external script.)",
	noteScript5 : "(Specifies the scripting language as a content-type (MIME type).)",
	noteScript6 : "(Defines the character encoding that the script uses.)",
	noteScript7 : "The HTML <strong>&#60;script&#62;</strong> tag is used for declaring a script (such as JavaScript) within your HTML document.<br /><br /><br />",
	
	noteSelect1 : "Enter Select Name:",
	noteSelect2 : "Enter Select ID:",
	noteSelect3 : "Enter Select Value:",
	noteSelect4 : "(Optional)",
	noteSelect5 : "(Optional)",
	noteSelect6 : "(Optional)",
	noteSelect7 : "The HTML <strong>&#60;select&#62;</strong> tag is used for defining a select list.<br /><br />This element is used in conjunction with the <strong>&#60;option&#62;</strong> element to produce a list of options that the user can choose from.<br /><br />Also see <strong>&#60;optgroup&#62;</strong> element for grouping your option items.<br /><br /><br />",
	
	noteSource1 : "Enter Source 'Source':",
	noteSource2 : "Enter Source Type:",
	noteSource3 : "Enter Source Media:",
	noteSource4 : "(Specifies the location of the audio/video file. Its value must be the URI of an audio file.)",
	noteSource5 : "(Specifies the type of the embedded content. If specified, the value must be a MIME type.)",
	noteSource6 : "(Specifies the type of media resource, so the browser can determine whether it can play it or not.)",
	noteSource7 : "The HTML <strong>&#60;source&#62;</strong> tag is used to specify multiple media resources on media elements (such as <strong>&#60;audio&#62;</strong> and <strong>&#60;video&#62;</strong>).<br /><br />This element allows you to specify alternative video and audio files which the browser may choose from based on its media type or codec support.<br /><br />The <strong>&#60;source&#62;</strong> tag was introduced in HTML 5.<br /><br /><br />",
	
	noteSpan1 : "Enter Style Attributes:",
	noteSpan2 : "(Optional)",
	noteSpan3 : "The HTML <strong>&#60;span&#62;</strong> tag is used for grouping and applying styles to inline elements.<br /><br />The difference between the <strong>&#60;span&#62;</strong> tag and the <strong>&#60;div&#62;</strong> tag is that the <strong>&#60;span&#62;</strong> tag is used with inline elements whilst the <strong>&#60;div&#62;</strong> tag is used with block-level content.<br /><br /><br />",
	
	noteStyle1 : "Enter Style Type:",
	noteStyle2 : "Enter Style Media:",
	noteStyle3 : "(Specifies the style sheet language as a content-type (MIME type).)",
	noteStyle4 : "(Specifies the device that the styles apply to. Must be a valid media query.)",
	noteStyle5 : "The HTML <strong>&#60;style&#62;</strong> tag is used for declaring style sheets within your HTML document.<br /><br />Each HTML document can contain multiple <strong>&#60;style&#62;</strong> tags.<br /><br />In HTML 5, the <strong>&#60;style&#62;</strong> tag can be used within the <strong>&#60;body&#62;</strong> element (or its child elements) as long as the scoped attribute is used. If the scoped attribute is not used, each <strong>&#60;style&#62;</strong> tag must be located between the <strong>&#60;head&#62;</strong> tags (or a <strong>&#60;noscript&#62;</strong> element that is a child of a <strong>&#60;head&#62;</strong> element).<br /><br /><br />",
	
	noteTable1 : "Enter Table Border:",
	noteTable2 : "Enter Table Cell Padding:",
	noteTable3 : "Enter Table Cell Spacing:",
	noteTable4 : "Enter Table Summary:",
	noteTable5 : "Enter Table Width:",
	noteTable6 : "Enter Table Style Attributes:",
	noteTable7 : "(Specifies the width, style, and color of the border.)",
	noteTable8 : "(Specifies the space between the cell wall and the cell content.)",
	noteTable9 : "(Specifies the space between cells.)",
	noteTable10 : "(Specifies a summary of the content of a table.)",
	noteTable11 : "(Specifies the width of the table.)",
	noteTable12 : "(Specifies custom css styles.)",
	noteTable13 : "The HTML <strong>&#60;table&#62;</strong> tag is used for defining a table. The <strong>&#60;table&#62;</strong> tag contains other tags that define the structure of the table.<br /><br /><br />",
	
	noteTd1 : "Enter TD Column Span:",
	noteTd2 : "Enter TD Row Span:",
	noteTd3 : "Select TD Vertical Align:",
	noteTd4 : "Select TD Horizontal Align:",
	noteTd5 : "Enter TD Headers:",
	noteTd6 : "Select TD Scope:",
	noteTd7 : "(Specifies the number of columns the current cell spans across.)",
	noteTd8 : "(Specifies the number of rows the current cell spans across.)",
	noteTd9 : "(Vertically aligns the content in a cell.)",
	noteTd10 : "(Horizontally aligns the content in a cell.)",
	noteTd11 : "(Specifies a space-separated list of header cells that contain information about this cell.)",
	noteTd12 : "(This attribute is used on header cells and specifies the cells that will use this header's information.)",
	noteTd13 : "The HTML <strong>&#60;td&#62;</strong> tag is used for specifying a cell (or table data) within a table.<br /><br />This tag must be nested inside a <strong>&#60;tr&#62;</strong> tag, which in turn must also be nested correctly.<br /><br /><br />",
	
	noteTextarea1 : "Enter Textarea Name:",
	noteTextarea2 : "Enter Textarea Rows:",
	noteTextarea3 : "Enter Textarea Columns:",
	noteTextarea4 : "Enter Textarea Form ID:",
	noteTextarea5 : "Enter Textarea Placeholder Text:",
	noteTextarea6 : "(Assigns a name to the input control.)",
	noteTextarea7 : "(The value must be a non-negative integer greater than zero (i.e. a number). The default value is 2.)",
	noteTextarea8 : "(The value must be a non-negative integer greater than zero (i.e. a number). The default value is 20.)",
	noteTextarea9 : "(Specifies the ID of a form to which this control belongs.)",
	noteTextarea10 : "(Provides a hint to the user to help them complete the textarea.)",
	noteTextarea11 : "The HTML <strong>&#60;textarea&#62;</strong> tag is used within a form to declare a textarea element - a control that allows the user to input text over multiple rows.<br /><br /><br />",
	
	noteTh1 : "Enter TH Column Span:",
	noteTh2 : "Enter TH Row Span:",
	noteTh3 : "Select TH Vertical Align:",
	noteTh4 : "Select TH Horizontal Align:",
	noteTh5 : "Enter TH Headers:",
	noteTh6 : "Select TH Scope:",
	noteTh7 : "(Specifies the number of columns the current cell spans across.)",
	noteTh8 : "(Specifies the number of rows the current cell spans across.)",
	noteTh9 : "(Vertically aligns the content in a cell.)",
	noteTh10 : "(Horizontally aligns the content in a cell.)",
	noteTh11 : "(Specifies a space-separated list of header cells that contain information about this cell.)",
	noteTh12 : "(This attribute is used on header cells and specifies the cells that will use this header's information.)",
	noteTh13 : "The HTML <strong>&#60;th&#62;</strong> tag is used for specifying a header cell (or table header) within a table.<br /><br />This tag must be nested inside a <strong>&#60;tr&#62;</strong> tag, which in turn must be nested inside a <strong>&#60;table&#62;</strong> tag.<br /><br /><br />",
	
	noteTr1 : "Select TR Vertical Align:",
	noteTr2 : "Select TR Horizontal Align:",
	noteTr3 : "Enter TR Style Attributes:",
	noteTr4 : "(Vertically aligns the content in a cell.)",
	noteTr5 : "(Horizontally aligns the content in a cell.)",
	noteTr6 : "(Optional)",
	noteTr7 : "The HTML <strong>&#60;tr&#62;</strong> tag is used for specifying a table row within a table. A table row contains one or more <strong>&#60;td&#62;</strong> and/or <strong>&#60;th&#62;</strong> tags which determine individual cells/columns.<br /><br /><br />",
	
	noteTrack1 : "Enter Track Source:",
	noteTrack2 : "Enter Track Source Language:",
	noteTrack3 : "Enter Track Kind:",
	noteTrack4 : "Enter Track Label:",
	noteTrack5 : "(Specifies the URL of the text track data. Required attribute.)",
	noteTrack6 : "(Specifies the language of the text track. The value must be a valid BCP 47 language tag. This attribute is required if the element's kind attribute is 'subtitles'.)",
	noteTrack7 : "(Specifies the kind of text track. This attribute is an enumerated attribute.)",
	noteTrack8 : "(Specifies that the track is to be enabled if the user's preferences do not indicate that another track would be more appropriate. There must not be more than one track element with the same parent node with the default attribute specified.)",
	noteTrack9 : "The HTML <strong>&#60;track&#62;</strong> tag is used to specify external timed text tracks for media elements (i.e. the <strong>&#60;video&#62;</strong> element and the <strong>&#60;audio&#62;</strong> element). The text tracks specified with the <strong>&#60;track&#62;</strong> tag could include subtitles, captions, descriptions, chapters, and metadata.<br /><br /><br />",
	
	noteUl1 : "Enter Style Attributes:",
	noteUl2 : "(Optional)",
	noteUl3 : "The HTML <strong>&#60;ul&#62;</strong> tag is used for specifying an unordered list (or un-numbered list).<br /><br />Also see <strong>&#60;ol&#62;</strong> for ordered (numbered) lists and <strong>&#60;menu&#62;</strong> for menu lists.<br /><br /><br />",
	
	noteVideo1 : "Enter Video Source:",
	noteVideo2 : "Enter Video Poster:",
	noteVideo3 : "Enter Video Width:",
	noteVideo4 : "Enter Video Height:",
	noteVideo5 : "(Specifies the location of the video file. Its value must be the URI of a video file.)",
	noteVideo6 : "(Specifies an image to use while the video is unavailable (i.e. it hasn't loaded yet). This is typically an image of one of the first frames of the video. If supplied, the value must be a valid URL of an image.)",
	noteVideo7 : "(Specifies the width, in pixels, to display the video.)",
	noteVideo8 : "(Specifies the height, in pixels, to display the video.)",
	noteVideo9 : "The HTML <strong>&#60;video&#62;</strong> tag is used to specify video on an HTML document. For example, you could embed a music video on your web page for your visitors to listen to and watch.<br /><br />Any content between the opening and closing <strong>&#60;video&#62;</strong> tags is fallback content. This content is displayed only by browsers that don't support the <strong>&#60;video&#62;</strong> tag.<br /><br /><br />",
	
	
	bottomnote : "<strong>Wordpress Users</strong>: This list is overly exhausive. Not all options can be used inside the content editor. All tags were listed for this plugin to be cross-platform compatible. For usage, simply click the desired tag and it will be inserted into the content editor, wrapping any selected content.",
	bottomnote2 : "<a target=\"_blank\" href=\"http://www.plugins.joshlobe.com/contact/\"><strong>Report Bugs or Issues</a></strong> | This plugin is a work in progress. Some functionality may not currently work properly, or at all.",
	
    yes:"Yes",
    no:"No"
});