<?php

/* space == separator */

$emoticons=array();

$emoticons[]=':alien: alien.png';
$emoticons[]=':angry: angry.png';
$emoticons[]=':blink: blink.png';
$emoticons[]=':blush: blush.png';
$emoticons[]=':cheerful: cheerful.png';
$emoticons[]=':cool: cool.png';
$emoticons[]=':cwy: cwy.png';
$emoticons[]=':devil: devil.png';
$emoticons[]=':dizzy: dizzy.png';
$emoticons[]=':ermm: ermm.png';
$emoticons[]=':getlost: getlost.png';
$emoticons[]=':grin: grin.png';
$emoticons[]=':happy: happy.png';
$emoticons[]=':heart: heart.png';
$emoticons[]=':kissing: kissing.png';
$emoticons[]=':laughing: laughing.png';
$emoticons[]=':ninja: ninja.png';
$emoticons[]=':pinch: pinch.png';
$emoticons[]=':pouty: pouty.png';
$emoticons[]=':sad: sad.png';
$emoticons[]=':shocked: shocked.png';
$emoticons[]=':sick: sick.png';
$emoticons[]=':sideways: sideways.png';
$emoticons[]=':silly: silly.png';
$emoticons[]=':sleeping: sleeping.png';
$emoticons[]=':smile: smile.png';
$emoticons[]=':tongue: tongue.png';
$emoticons[]=':unsure: unsure.png';
$emoticons[]=':w00t: w00t.png';
$emoticons[]=':wassat: wassat.png';
$emoticons[]=':whistling: whistling.png';
$emoticons[]=':wink: wink.png';
$emoticons[]=':wub: wub.png';

$aliases=array();
$aliases[]=':) smile.png';
$aliases[]=':( sad.png';
$aliases[]=';-) wink.png';
$aliases[]=':-) smile.png';
$aliases[]=':-( sad.png';
$aliases[]='lol laughing.png';
$aliases[]='rofl laughing.png';

?>