tinyMCE.addI18n('en.emotions_dlg',{
				Ahhhh:"Ahhhh",
				amazing:"Amazing",
				big_smile:"Big Smile",
				cry1:"Cry",
				electric_shock:"Electric Shock",
				exciting:"Exciting",
				eyes_dropped:"Eyes Dropped",
				girl:"Girl",
				grimace:"Grimace",
				haha:"Ha Ha",
				scorn:"Scorn",
				secret_smile:"Secret Smile",
				shame:"Shame",
				shocked:"Shocked",
				unhappy:"Unhappy",
				victory:"Victory",
				what:"What",
				Alien:"Alien",
				Blush:"Blush",
				Crying:"Crying",
				Cool1:"Cool",
				Devil:"Devil",
				Happy:"Happy",
				Huh:"Huh",
				Love:"Love",
				Sick:"Sick",
				Sleep:"Sleep",
				Smile1:"Smile1",
				Tear:"Tear",
				Tounge:"Tounge",
				cry:"Cry",
				cool:"Cool",
				desc:"Emotions",
				title:"Josh's Custom Emotions Menu:",
				usage:"Choose Wisely...",
				yell:"Yell",
				wink:"Wink",
				Wink1:"Wink",
				Yikes:"Yikes",
				undecided:"Undecided",
				tongue_out:"Tongue Out",
				surprised:"Surprised",
				smile:"Smile",
				sealed:"Sealed",
				money_mouth:"Money Mouth",
				laughing:"Laughing",
				kiss:"Kiss",
				innocent:"Innocent",
				frown:"Frown",
				foot_in_mouth:"Foot in Mouth",
				embarassed:"Embarassed",
				popoadore:"Adore",
				popoah:"Ahh!",
				popoangry:"Angry",
				popobaffle:"Baffle",
				popobeat_ball:"Hit with Ball",
				popobeat_brick:"Hit with Brick",
				popobig_smile:"Big Smile",
				popoboss:"Big Boss",
				popoburn_joss_stick:"Pray",
				popocanny:"Canny",
				popofurious:"Furious",
				popoconfident:"Confident",
				popoconfuse:"Confused",
				popocry:"Crying",
				popodoubt:"Doubt it!",
				popodribble:"Dribble",
				popoembarrassed:"Embarrassed",
				popofeel_good:"Feeling Good",
				popohaha:"Ha Ha",
				popohell_boy:"Hell Boy",
				popolook_down:"Yeah... Sure",
				popomatrix:"Matrix",
				popomisdoubt:"Oh Really?",
				popooh:"Ugh!",
				popoops:"Oops",
				poposad:"Sad",
				popostill_dreaming:"Still Dreaming",
				poposurrender:"I Surrender!",
				poposweet_kiss:"Sweet Kiss",
				popotired:"So Tired",
				popotoo_sad:"Too Sad",
				popowhat:"What?!"			
				});