<?php

/**
 * @file
 * Provide menus based on taxonomy field.
 */

module_load_include('inc', 'taxonomy_field_menu', 'taxonomy_field_menu.pathauto');

/**
 * Implements hook_menu().
 */
function taxonomy_field_menu_menu() {
  $items = array();
  $items['taxonomy_field_menu/%taxonomy_field_menu_menu_name/%taxonomy_field_menu_tid'] = array(
    'title' => 'Term',
    'title callback' => 'taxonomy_term_title',
    'title arguments' => array(2),
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'taxonomy_field_menu_term_custom_page',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
    'file' => 'taxonomy_field_menu.page.inc',
  );
  $items['admin/structure/taxonomy_field_menu'] = array(
    'title' => 'Taxonomy field menus list',
    'description' => 'Administration of taxonomy field menu lists.',
    'page callback' => 'taxonomy_field_menu_overview_page',
    'access arguments' => array('administer content types'),
    'file' => 'taxonomy_field_menu.page.inc',
  );

  return $items;
}

/**
 * Taxonomy field menu load menu function.
 *
 * @param string $menu_name
 *   Load taxonomy field menu object from database, by menu name.
 *
 * @return object
 *   A taxonomy field menu object, or FALSE.
 */
function taxonomy_field_menu_menu_name_load($menu_name) {
  $menu = _taxonomy_field_menu_get_menus(NULL, NULL, $menu_name);
  if (!empty($menu)) {
    return $menu;
  }
  return FALSE;
}

/**
 * Load term obejct for tid.
 *
 * This load function is mainly used to make sure the custom term path should
 * exist for one term.
 *
 * @param int $tid
 *   Term's tid, which will be used to load term object.
 *
 * @return object
 *   A term object.
 */
function taxonomy_field_menu_tid_load($tid) {
  if ($term = taxonomy_term_load($tid)) {
    // Ideally, it should detect whether this taxonomy field menu has enabled
    // custom term page. If this menu doesn't use our own term page, we
    // return false to tell users this page is illegal.
    // The challenge is we need to show custom term page links inside menus.
    // Consequently, we can't decide which taxonomy field menu context
    // it could be. So, simply return $term here.
    return $term;
  }
  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * We need to alter taxonomy field for nodes.
 */
function taxonomy_field_menu_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  // Only work eith nodes now.
  if ($form['#instance']['entity_type'] == 'node' && $form['#field']['type'] == 'taxonomy_term_reference') {
    $field = $form['#field'];
    $field_name = $field['field_name'];

    // Get taxonomy field menu object for this field.
    $taxonomy_field_menu = _taxonomy_field_menu_get_menus(NULL, $field_name);
    $form['menu_object'] = array(
      '#type' => 'value',
      '#value' => $taxonomy_field_menu,
    );

    $form['taxonomy_field_menu'] = array(
      '#type' => 'fieldset',
      '#title' => t('Taxonomy field menu setting'),
    );

    $description = '';
    if (!field_has_data($field_name)) {
      $description .= t("You have to add data for this field <b>FIRSTLY</b>. Then this setting could be enabled.<br />");
    }
    $description .= t("If taxonomy field menu is enabled for this field, it can be managed at default menu UI 'admin/structure/menu' too.<br /> NOTE: This setting is field sensitive. If this setting has been updated from checked to unchecked, taxonomy field menu for this field name will all be deleted!");

    $form['taxonomy_field_menu']['menu_flag'] = array(
      '#title' => t('Enable taxonomy field menu for this field'),
      '#type' => 'checkbox',
      '#default_value' => isset($taxonomy_field_menu->menu_name) ? 1 : 0,
      '#description' => $description,
      '#disabled' => field_has_data($field_name) ? FALSE : TRUE,
    );
    // Add a checkbox when user tries to delete taxonomy field menu for this
    // field.
    if ((isset($form_state['delete_taxonomy_field_menu']))) {
      $form['taxonomy_field_menu']['menu_flag']['#value'] = 0;
      $form['taxonomy_field_menu']['menu_flag']['#disabled'] = TRUE;
      $form['taxonomy_field_menu']['delete_menu_flag'] = array(
        '#type' => 'checkbox',
        '#title' => t('I REALLY want to delete taxonomy field menu for this field!'),
        '#states' => array(
          'visible' => array(
            ':input[name="menu_flag"]' => array('checked' => FALSE),
          ),
        ),
      );
    }
    module_load_include('inc', 'menu', 'menu.admin');
    $suggested_machine_name = preg_replace('/_/', '-', $field_name);
    $suggested_machine_name = substr($suggested_machine_name, 0, MENU_MAX_MENU_NAME_LENGTH_UI);
    $form['taxonomy_field_menu']['menu_machine_name'] = array(
      '#title' => t('Machine name for this taxonomy field menu'),
      '#type' => 'machine_name',
      '#required' => FALSE,
      '#field_prefix' => isset($taxonomy_field_menu->menu_name) ? '' : 'menu-',
      '#default_value' => isset($taxonomy_field_menu->menu_name) ? $taxonomy_field_menu->menu_name : $suggested_machine_name,
      '#maxlength' => MENU_MAX_MENU_NAME_LENGTH_UI,
      '#size' => 30,
      '#description' => t('A unique name to construct the URL for taxonomy field menu.
        It must only contain lowercase letters, numbers and hyphens.'),
      '#machine_name' => array(
        'exists' => 'menu_edit_menu_name_exists',
        'source' => array('title'),
        'replace_pattern' => '[^a-z0-9-]+',
        'replace' => '-',
      ),
      '#disabled' => isset($taxonomy_field_menu->menu_name),
      '#states' => array(
        'visible' => array(
          ':input[name="menu_flag"]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['taxonomy_field_menu']['configs'] = array(
      '#type' => 'fieldset',
      '#title' => t('Configuration for this taxonomy field menu.'),
      '#states' => array(
        'visible' => array(
          ':input[name="menu_flag"]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['taxonomy_field_menu']['configs']['custom_page'] = array(
      '#type' => 'checkbox',
      '#default_value' => isset($taxonomy_field_menu->custom_page) ? $taxonomy_field_menu->custom_page : 0,
      '#title' => t('Enable custom term page for this taxonomy field menu.'),
      '#disabled' => isset($taxonomy_field_menu->menu_name),
    );
    $form['taxonomy_field_menu']['configs']['child_node'] = array(
      '#type' => 'checkbox',
      '#default_value' => isset($taxonomy_field_menu->child_node) ? $taxonomy_field_menu->child_node : 0,
      '#title' => t("Add child nodes for custom term page."),
      '#states' => array(
        'visible' => array(
          ':input[name="custom_page"]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['taxonomy_field_menu']['configs']['url_alias'] = array(
      '#type' => 'checkbox',
      '#default_value' => isset($taxonomy_field_menu->url_alias) ? $taxonomy_field_menu->url_alias : 0,
      '#title' => t("Enable url alias/pathauto integration with this taxonomy field menu."),
      '#disabled' => isset($taxonomy_field_menu->menu_name),
      '#states' => array(
        'visible' => array(
          ':input[name="custom_page"]' => array('checked' => TRUE),
        ),
      ),
    );
    $form['taxonomy_field_menu']['configs']['sync_node'] = array(
      '#type' => 'checkbox',
      '#default_value' => isset($taxonomy_field_menu->sync_node) ? $taxonomy_field_menu->sync_node : 0,
      '#title' => t("Synchronize taxonomy field menu when a node is updated."),
      '#disabled' => isset($taxonomy_field_menu->menu_name),
    );
    $form['taxonomy_field_menu']['configs']['sync_term'] = array(
      '#type' => 'checkbox',
      '#default_value' => isset($taxonomy_field_menu->sync_term) ? $taxonomy_field_menu->sync_term : 0,
      '#title' => t("Synchronize taxonomy field menu when a term is updated."),
      '#disabled' => isset($taxonomy_field_menu->menu_name),
    );

    $link = l(t('README.txt'), drupal_get_path('module', 'taxonomy_field_menu') . "/README.txt");
    $form['taxonomy_field_menu']['configs']['help'] = array(
      '#markup' => t("Ideally, they should be checked all. For details of these configurations, see ") . $link,
    );
    if (isset($taxonomy_field_menu->menu_name)) {
      $form['taxonomy_field_menu']['rebuild'] = array(
        '#type' => 'fieldset',
        '#title' => t('Rebuild this taxonomy field menu'),
        '#states' => array(
          'visible' => array(
            ':input[name="menu_flag"]' => array('checked' => TRUE),
          ),
        ),
      );
      $form['taxonomy_field_menu']['rebuild']['rebuild_button'] = array(
        '#type' => 'submit',
        '#value' => t('Rebuild'),
        '#submit' => array('taxonomy_field_menu_rebuild_term_links'),
      );
      $form['taxonomy_field_menu']['rebuild']['reset_button'] = array(
        '#type' => 'submit',
        '#value' => t('Reset'),
        '#submit' => array('taxonomy_field_menu_reset_term_links'),
      );
      $form['taxonomy_field_menu']['rebuild']['rebuild_des'] = array(
        '#prefix' => '<div>',
        '#markup' => t("<div>When clicks 'Rebuild' button, taxonomy field menu for this field will disable(Note: not delete) term links which don't have any child node links. It will recursively check child terms too. <br /> Do this when everything is ready and you want to hide those term links from users, or you are experiencing term links enable/disable issues. You can manually do this at default menu ui too.</div> <div>When clicks 'Reset' button, all term links will be enabled.</div>"),
        '#suffix' => '</div>',
        '#states' => array(
          'visible' => array(
            ':input[name="menu_flag"]' => array('checked' => TRUE),
          ),
        ),
      );
    }

    $form['#submit'][] = 'taxonomy_field_menu_field_menu_submit';
    $form['#validate'][] = 'taxonomy_field_menu_field_menu_validate';
  }
}

/**
 * Submit handler to rebuild taxonomy field menu.
 *
 * Disable term links from taxonomy field menu, when this term and its
 * child terms don't have any nodes connected.
 */
function taxonomy_field_menu_rebuild_term_links($form, $form_state) {
  $taxonomy_field_menu = $form_state['values']['menu_object'];
  if (!isset($taxonomy_field_menu->menu_name)) {
    drupal_set_message(t("Sorry, there's no taxonomy field menu associated with this field."));
    return NULL;
  }
  $transaction = db_transaction();
  try {
    // Override default value.
    $taxonomy_field_menu->child_node = 1;
    $terms = taxonomy_get_tree($taxonomy_field_menu->vid);
    foreach ($terms as $term) {
      $nids = taxonomy_field_menu_get_term_all_nodes($term, $taxonomy_field_menu);
      // Disable this term link from taxonomy field menu.
      if (empty($nids)) {
        _taxonomy_field_menu_disable_term_link($term, $taxonomy_field_menu);
      }
      else {
        _taxonomy_field_menu_enable_term_link($term, $taxonomy_field_menu);
      }
    }
    drupal_set_message(t('taxonomy field menus have been rebuilt sucessfully!'));
  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('taxonomy_field_menu', $e);
    throw $e;
  }
}

/**
 * Submit handler to reset taxonomy field menu.
 *
 * Enable term links from taxonomy field menu, EVEN this term and its child
 * terms don't have any nodes connected.
 */
function taxonomy_field_menu_reset_term_links($form, $form_state) {
  $taxonomy_field_menu = $form_state['values']['menu_object'];
  if (!isset($taxonomy_field_menu->menu_name)) {
    drupal_set_message(t("Sorry, there's no taxonomy field menu associated with this field."));
    return NULL;
  }
  $transaction = db_transaction();
  try {
    // Override default value.
    $taxonomy_field_menu->child_node = 1;
    $terms = taxonomy_get_tree($taxonomy_field_menu->vid);
    foreach ($terms as $term) {
      _taxonomy_field_menu_enable_term_link($term, $taxonomy_field_menu);
    }
    drupal_set_message(t('taxonomy field menus have been reset sucessfully!'));
  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('taxonomy_field_menu', $e);
    throw $e;
  }
}

/**
 * Validate handler for taxonomy field ui form.
 */
function taxonomy_field_menu_field_menu_validate(&$form, &$form_state) {
  $taxonomy_field_menu = $form_state['values']['menu_object'];
  $menu_flag = $form_state['values']['menu_flag'];
  if (!$menu_flag && isset($taxonomy_field_menu->menu_name)) {
    if (isset($form_state['values']['delete_menu_flag']) && $form_state['values']['delete_menu_flag']) {
      // If user is sure to delete taxonomy field menu for this field,
      // do nothing.
    }
    else {
      $form_state['rebuild'] = TRUE;
      $form_state['delete_taxonomy_field_menu'] = 1;
      drupal_set_message(t("Do you really want to delete taxonomy field menu for this field? If so, please confirm in the last checkbox."), 'warning');
    }
  }
}

/**
 * Submit handler for taxonomy field ui form.
 *
 * There're three ui for user to manage taxonomy field menu, i.e, field
 * edit ui, term edit ui, default menu ui. Here's the back-end handling
 * for field ui.
 */
function taxonomy_field_menu_field_menu_submit($form, &$form_state) {
  $taxonomy_field_menu = $form_state['values']['menu_object'];
  $field_name = $form['#field']['field_name'];
  $field = $form['#field'];

  $menu_flag = $form_state['values']['menu_flag'];
  $menu['title'] = 'Taxonomy field menu for ' . $field_name;
  $menu['description'] = 'taxonomy field menu for ' . $field_name;
  $path = 'admin/structure/menu/manage/';

  $transaction = db_transaction();
  try {
    // Add a new taxonomy field menu when this field didn't have one.
    if ($menu_flag && !isset($taxonomy_field_menu->menu_name)) {
      // Add 'menu-' to the menu name to help avoid name-space conflicts.
      $menu['menu_name'] = 'menu-' . $form_state['values']['menu_machine_name'];

      // Add all terms links to this new menu.
      // It only counts the first vocabulary. If your contrib code uses
      // multiple vocabularies, the others will be ignored.
      $vocabulary_name = $form['#field']['settings']['allowed_values'][0]['vocabulary'];
      $vocabulary_ob = taxonomy_vocabulary_machine_name_load($vocabulary_name);

      // Manually rebuild a new taxonomy_field_menu object.
      $taxonomy_field_menu = array(
        'field_name' => $field_name,
        'vid' => $vocabulary_ob->vid,
        'menu_name' => $menu['menu_name'],
        'custom_page' => $form_state['values']['custom_page'],
        'child_node' => $form_state['values']['child_node'],
        'sync_node' => $form_state['values']['sync_node'],
        'sync_term' => $form_state['values']['sync_term'],
        'node_type' => arg(4),
        'url_alias' => $form_state['values']['url_alias'],
      );
      $taxonomy_field_menu = (object) $taxonomy_field_menu;
      // Add record to {taxonomy_field_menu}.
      _taxonomy_field_menu_insert_menu($taxonomy_field_menu);

      // Now save menu and links.
      $link['link_title'] = $menu['title'];
      $link['link_path'] = $path . $menu['menu_name'];
      $link['router_path'] = $path . '%';
      $link['module'] = 'taxonomy_field_menu';
      $link['plid'] = db_query("SELECT mlid FROM {menu_links} WHERE link_path = :link AND module = :module", array(
        ':link' => 'admin/structure/menu',
        ':module' => 'system',
      ))->fetchField();

      menu_link_save($link);
      menu_save($menu);

      // Add batch support for this handling.
      $batch = array(
        'title' => t('Initialize taxonomy field menu for field @field', array('@field' => $field_name)),
        'operations' => array(
          array('taxonomy_field_menu_initialize_taxonomy_field_menu', array($taxonomy_field_menu)),
        ),
      );
      batch_set($batch);

      drupal_set_message(t('taxonomy field menu for field @field has been created sucessfully.', array('@field' => $field_name)));
      watchdog('taxonomy field menu', 'taxonomy field menu for field @field has been created sucessfully.', array('@field' => $field_name));
    }
    elseif ($menu_flag && isset($taxonomy_field_menu->menu_name)) {
      // Update this taxonomy field menu.
      $taxonomy_field_menu->child_node = $form_state['values']['child_node'] ? 1 : 0;
      _taxonomy_field_menu_update_taxonomy_field_menu($taxonomy_field_menu);
    }
    elseif (!$menu_flag && isset($taxonomy_field_menu->menu_name)) {
      _taxonomy_field_menu_delete_menu($taxonomy_field_menu);

      drupal_set_message(t('taxonomy field menu for field @field has been deleted sucessfully.', array('@field' => $field_name)));
      watchdog('taxonomy field menu', 'taxonomy field menu for field @field has been deleted sucessfully.', array('@field' => $field_name));
    }
  }
  catch(Exception $e) {
    $transaction->rollback();
    watchdog_exception('taxonomy_field_menu', $e);
    throw $e;
  }
}

/**
 * Initialize taxonomy field menu for a taxonomy field.
 *
 * @param object $taxonomy_field_menu
 *   This taxonomy_field_menu object is manually created in code according
 *   to user's input from field edit ui. As there's a db transaction going,
 *   it's not possible to get $taxonomy_field_menu object from db before
 *   the whole initializing process is over.
 */
function taxonomy_field_menu_initialize_taxonomy_field_menu($taxonomy_field_menu, &$context) {
  // At this scenario, we need to reset $taxonomy_field_menu's sync_term
  // property.
  $taxonomy_field_menu->sync_term = 1;
  $terms = taxonomy_get_tree($taxonomy_field_menu->vid);
  $tids = array();
  if (!empty($terms)) {
    $count = count($terms);
    $context['sandbox']['progress'] = 0;
    // Add every term link, including associated nodes into {menu_links}.
    foreach ($terms as $term) {
      if (!isset($tids[$term->tid])) {
        $tids[$term->tid] = 1;
      }
      // If this term has already been inserted, we continue;
      else {
        continue;
      }
      $term_mlid = _taxonomy_field_menu_insert_term_link($term, $taxonomy_field_menu);
      // If this taxonomy field menu doesn't sync nodes, we continue;
      if (!$taxonomy_field_menu->sync_node) {
        continue;
      }
      $nids = _taxonomy_field_menu_get_term_field_nodes($term->tid, $taxonomy_field_menu->field_name);
      foreach ($nids as $nid) {
        // Add node link to {menu_links}.
        $title = _taxonomy_field_menu_get_node_title($nid);
        $node_link = array(
          'link_path' => 'node/' . $nid,
          'link_title' => $title,
          'menu_name' => $taxonomy_field_menu->menu_name,
          'plid' => $term_mlid,
          'router_path' => 'node/%',
          'module' => 'taxonomy_field_menu',
        );
        menu_link_save($node_link);
      }
      $context['sandbox']['progress']++;
      if ($context['sandbox']['progress'] != $count) {
        $context['sandbox']['finished'] = $context['sandbox']['progress'] / $count;
      }
    }
    watchdog('taxonomy field menus', 'taxonomy field menu for field :field_name has been created.', array(':field_name' => $taxonomy_field_menu->field_name));
  }
  $context['results'][] = 'Well done!';
  $context['message'] = 'Sucessfully initialized';
}

/**
 * Get term's all nodes, including possible child term's node.
 *
 * @param object $top_term
 *   This is the term object we need to process. The reason to call it
 *   'top_term', is because it could have child terms, and we need to get
 *   those child terms' nodes as well when $taxonomy_field_menu has specified
 *   child_node property.
 *
 * @param object $taxonomy_field_menu
 *   The taxonomy field menu object this term is working on. One notable thing
 *   is its child_node property will decide whether this functions collects
 *   child terms' nodes for $top_term.
 *
 * @return array
 *   An array nids associated to this $top_term via $taxonomy_field_menu. Or
 *   an empty array if no nid is found.
 */
function taxonomy_field_menu_get_term_all_nodes($top_term, $taxonomy_field_menu) {
  // Get nids connected to this term inside the menu.
  $nids = _taxonomy_field_menu_get_term_field_nodes($top_term->tid, $taxonomy_field_menu->field_name);

  // Need to add child term's nodes, if this taxonomy field menu requires it.
  if ($taxonomy_field_menu->child_node) {
    $tids = array($top_term->tid);
    while ($tids) {
      $next_generations = array();
      foreach ($tids as $tid) {
        $children = taxonomy_get_children($tid, $taxonomy_field_menu->vid);
        foreach ($children as $child) {
          $child_nids = _taxonomy_field_menu_get_term_field_nodes($child->tid, $taxonomy_field_menu->field_name);
          $nids = array_merge($nids, $child_nids);
          $next_generations[] = $child->tid;
        }
      }
      $tids = $next_generations;
    }
  }
  return $nids;
}

/**
 * Implements hook_node_insert().
 *
 * Add this node into taxonomy field menu, if condition is met.
 */
function taxonomy_field_menu_node_insert($node) {
  _taxonomy_field_menu_insert_node_link($node);
}

/**
 * Implements hook_node_update().
 *
 * Delete this node link from taxonomy field menu and generate it again.
 */
function taxonomy_field_menu_node_update($node) {
  // A better way is to detect whether ths node's taxonomy field has changed
  // firstly. If changed, we do delete and insert actions. However, since
  // this node link could be updated at default menu UI, it makes no sense to
  // compare this node itself at all.
  // Here we simply ignore the compare process. It means any changes about
  // this node link made through default menu UI will be reset to the newest
  // node taxonomy field status.
  _taxonomy_field_menu_delete_node_link($node);
  _taxonomy_field_menu_insert_node_link($node);
}

/**
 * Implements hook_node_delete().
 *
 * Delete this node from taxonomy field menu, if condition is met.
 */
function taxonomy_field_menu_node_delete($node) {
  _taxonomy_field_menu_delete_node_link($node);
}

/**
 * Implements hook_node_type_delete().
 *
 * Delete taxonomy field menus with this node type, if condition is met.
 */
function taxonomy_field_menu_node_type_delete($info) {
  $taxonomy_field_menus = _taxonomy_field_menu_get_menus();
  $fields = field_info_field_map();
  foreach ($taxonomy_field_menus as $taxonomy_field_menu) {
    if (isset($fields[$taxonomy_field_menu->field_name])) {
      $bundles = $fields[$taxonomy_field_menu->field_name]['bundles'];
      if (!isset($bundles['node'])) {
        continue;
      }
      $bundles = $bundles['node'];
      // If this deleted type is the only bundle for taxonomy field menu's
      // field, delete this taxonomy field menu too.
      if (count($bundles) > 1) {
        // If this menu has used this type as token, we need to delete it.
        // Assign another random available node type for this menu.
        if ($taxonomy_field_menu->node_type == $info->type) {
          foreach ($bundles as $bundle) {
            if ($taxonomy_field_menu->node_type != $bundle) {
              // Update node_type property.
              $taxonomy_field_menu->node_type = $bundle;
              _taxonomy_field_menu_update_taxonomy_field_menu($taxonomy_field_menu);
              // We don't handle url alias update here. This is the basic
              // design of pathauto. Admin could use bulk update for url
              // alias change.
              break;
            }
          }
        }
        continue;
      }
      if (in_array($info->type, $bundles)) {
        _taxonomy_field_menu_delete_menu($taxonomy_field_menu);
      }
    }
  }
}

/**
 * Implements hook_field_delete_field().
 *
 * Delete taxonomy field menu for this term field, if this field has a
 * taxonomy field menu.
 */
function taxonomy_field_menu_field_delete_field($field) {
  if ($field['type'] == 'taxonomy_term_reference') {
    // Get taxonomy field menu machine name, if there's one.
    $taxonomy_field_menu = _taxonomy_field_menu_get_menus(NULL, $field['field_name']);
    if ($taxonomy_field_menu) {
      // Need to delete this field's taxonomy field menu.
      _taxonomy_field_menu_delete_menu($taxonomy_field_menu);
    }
  }
}

/**
 * Implements hook_taxonomy_term_delete().
 *
 * Delete taxonomy field menu for this term field, if condition is met.
 */
function taxonomy_field_menu_taxonomy_term_delete($term) {
  $taxonomy_field_menus = _taxonomy_field_menu_get_menus($term->vid);
  // Get one mlid, and decide whether need to delete its path alias.
  foreach ($taxonomy_field_menus as $taxonomy_field_menu) {
    if (!$taxonomy_field_menu->sync_term) {
      continue;
    }
    taxonomy_field_menu_delete_term_path_alias($term, $taxonomy_field_menu);
    $mlid = _taxonomy_field_menu_get_term_mlid($term->tid, $taxonomy_field_menu);
    menu_link_delete($mlid);
  }
}

/**
 * Implements hook_taxonomy_term_insert().
 *
 * Insert taxonomy field menu for this term field, if condition is met.
 */
function taxonomy_field_menu_taxonomy_term_insert($term) {
  $taxonomy_field_menus = _taxonomy_field_menu_get_menus($term->vid);

  foreach ($taxonomy_field_menus as $taxonomy_field_menu) {
    _taxonomy_field_menu_insert_term_link($term, $taxonomy_field_menu);
  }
}

/**
 * Implements hook_taxonomy_term_update().
 *
 * Update each taxonomy field menu for this term, if condition is met.
 * What we care here is term name and term relation. Term name is going to
 * be used as link title, and term parent is going to decide its parent link.
 *
 * TODO: Needs to consider its parent link as customized link set by user
 * at default menu ui, which is probably not a term link.
 */
function taxonomy_field_menu_taxonomy_term_update($term) {
  _taxonomy_field_menu_taxonomy_term_update($term);
  drupal_set_message(t('Updated @term for its taxonomy field menu(s).', array('@term' => $term->name)));
}

/**
 * Implements hook_taxonomy_vocabulary_delete().
 *
 * Delete taxonomy field menu for this vocabulary, if condition is met.
 */
function taxonomy_field_menu_taxonomy_vocabulary_delete($vocabulary) {
  $taxonomy_field_menus = _taxonomy_field_menu_get_menus($vocabulary->vid);
  foreach ($taxonomy_field_menus as $taxonomy_field_menu) {
    // If this taxonomy field menu has set to not sync term, we continue.
    if (!$taxonomy_field_menu->sync_term) {
      continue;
    }
    _taxonomy_field_menu_delete_menu($taxonomy_field_menu);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for taxonomy_overview_terms().
 *
 * Delete taxonomy field menu for this term field, if condition is met.
 */
function taxonomy_field_menu_form_taxonomy_overview_terms_alter(&$form, &$form_state) {
  $form['#submit'][] = 'taxonomy_field_menu_term_overview_submit';
}

/**
 * Submit handler, reacting on form ID: taxonomy_overview_terms.
 */
function taxonomy_field_menu_term_overview_submit(&$form, &$form_state) {

  // Credits: Following condition code comes from taxonomy_menu module at d.g.
  // See https://drupal.org/project/taxonomy_menu.
  // This form has the following flow of buttons:
  // 1. [Save] --> rebuild taxonomy_menu
  // 2. [Reset to alphabetical] --> no rebuild yet
  // 3. [Reset to alphabetical][Reset to alphabetical] --> rebuild
  // 4. [Reset to alphabetical][Cancel] --> no rebuild
  // The code below avoids rebuilding after situation 2.
  if ($form_state['rebuild'] == FALSE && isset($form['#vocabulary']->vid)) {
    // Try to catch the 'Save' button.
    $vid = $form['#vocabulary']->vid;
  }
  elseif ($form_state['rebuild'] == TRUE && isset($form['#vocabulary']->vid)) {
    // Try to catch the 'Reset to alphabetical' button.
    $vid = NULL;
  }
  elseif ($form_state['rebuild'] == FALSE && isset($form['vid']['#value'])) {
    // Try to catch the second (confirming) 'Reset to alphabetical' button.
    $vid = $form['vid']['#value'];
  }
  else {
    // The button [Reset to alphabetical] [Cancel] does not call this page.
    $vid = NULL;
  }

  if (isset($vid)) {
    $terms = taxonomy_get_tree($vid);
    foreach ($terms as $term) {
      // Update each term.
      _taxonomy_field_menu_taxonomy_term_update($term);
    }
    drupal_set_message(t('Updated @vob for its taxonomy field menu(s).', array('@vob' => arg(3))));
  }
}

/**
 * Get term's FIRST parent's mlid.
 *
 * This parent exists in {menu_links} before this child term has been
 * inserted into {menu_links}.
 *
 * Anyway, multiple parents could lead to unpredicted results here. User
 * should avoid multiple term parents for this module.
 *
 * @param object $term
 *   Term object we are processing.
 *
 * @param object $taxonomy_field_menu
 *   taxonomy field menu object associated with this term, mainly used to
 *   provide taxonomy field menu's menu_name.
 *
 * @return int
 *   This term's parent term's mlid in {menu_links}, or 0 if none was found.
 */
function taxonomy_field_menu_get_term_parent_mlid($term, $taxonomy_field_menu) {
  // $term object may or may not contain its parents information, we use
  // following function to get its parents.
  $parents = taxonomy_get_parents($term->tid);
  $ptids = array_keys($parents);
  foreach ($ptids as $ptid) {
    $plid = _taxonomy_field_menu_get_term_mlid($ptid, $taxonomy_field_menu);
    if ($plid) {
      break;
    }
  }
  return isset($plid) ? $plid : 0;
}

/**
 * Insert a term link into {menu_links}.
 */
function _taxonomy_field_menu_insert_term_link($term, $taxonomy_field_menu) {
  // If this menu has been set to not sync term, we break.
  if (!$taxonomy_field_menu->sync_term) {
    return NULL;
  }
  $plid = taxonomy_field_menu_get_term_parent_mlid($term, $taxonomy_field_menu);
  // Insert this term's link for each taxonomy field menu.
  $link = array(
    'link_path' => 'taxonomy/term/' . $term->tid,
    'link_title' => $term->name,
    'menu_name' => $taxonomy_field_menu->menu_name,
    'weight' => $term->weight,
    'plid' => (!empty($plid)) ? $plid : 0,
    'router_path' => 'taxonomy/term/%',
    'module' => 'taxonomy_field_menu',
  );
  if ($taxonomy_field_menu->custom_page) {
    $link['link_path'] = 'taxonomy_field_menu/' . $taxonomy_field_menu->menu_name . '/' . $term->tid;
    $link['router_path'] = 'taxonomy_field_menu/%/%';
  }
  $term_mlid = menu_link_save($link);

  // Add path alias for this term.
  taxonomy_field_menu_insert_term_path_alias($term, $taxonomy_field_menu);
  return $term_mlid;
}

/**
 * Insert one node link into taxonomy field menu.
 *
 * @param object $node
 *   Node object we are processing.
 */
function _taxonomy_field_menu_insert_node_link($node) {
  $taxonomy_field_menus = _taxonomy_field_menu_get_menus();
  foreach ($taxonomy_field_menus as $taxonomy_field_menu) {
    // If this menu has set to not sync node, we continue.
    if (!$taxonomy_field_menu->sync_node) {
      continue;
    }
    $cache_flag = 1;
    $field_name = $taxonomy_field_menu->field_name;
    $menu_name = $taxonomy_field_menu->menu_name;

    if (isset($node->{$field_name})) {
      foreach ($node->{$field_name}['und'] as $delta => $value) {
        $plid = _taxonomy_field_menu_get_term_mlid($value['tid'], $taxonomy_field_menu);
        $link = array(
          'link_path' => 'node/' . $node->nid,
          'link_title' => $node->title,
          'menu_name' => $menu_name,
          'plid' => $plid,
          'router_path' => 'node/%',
          'module' => 'taxonomy_field_menu',
        );
        menu_link_save($link);
      }
    }
  }
}

/**
 * Delete one node's links from taxonomy field menu.
 *
 * @param object $node
 *   Node object we are processing.
 */
function _taxonomy_field_menu_delete_node_link($node) {
  $taxonomy_field_menus = _taxonomy_field_menu_get_menus();
  $menus = array();
  if ($taxonomy_field_menus) {
    foreach ($taxonomy_field_menus as $menu) {
      // If this menu has set to not sync node, we continue.
      if (!$menu->sync_node) {
        continue;
      }
      $menus[] = $menu->menu_name;
    }

    $query = db_select('menu_links', 'ml');
    $query->condition('ml.menu_name', $menus, 'IN')
      ->condition('ml.link_path', 'node/' . $node->nid)
      ->fields('ml', array('mlid'));
    $mlids = $query->execute()->fetchCol();

    foreach ($mlids as $mlid) {
      menu_link_delete($mlid);
    }
  }
}

/**
 * Update individual term link.
 *
 * @param object $term
 *   Term object we are processing.
 */
function _taxonomy_field_menu_taxonomy_term_update($term) {
  $transaction = db_transaction();
  try {
    $taxonomy_field_menus = _taxonomy_field_menu_get_menus($term->vid);
    // Iterate each taxonomy field menu.
    foreach ($taxonomy_field_menus as $taxonomy_field_menu) {
      // If this menu has set to not sync term, we continue.
      if (!$taxonomy_field_menu->sync_term) {
        continue;
      }
      $mlid = _taxonomy_field_menu_get_term_mlid($term->tid, $taxonomy_field_menu);
      if ($mlid) {
        $item = menu_link_load($mlid);
        // Update this term's link title, weight and its plid.
        $item['link_title'] = $term->name;
        $item['weight'] = $term->weight;
        $plid = taxonomy_field_menu_get_term_parent_mlid($term, $taxonomy_field_menu);
        // Override its parent link. If admin has added custom link as parent
        // link for this term in menu ui, it will be reset here. It's admin's
        // responsibility to take care of these custom parent links.
        // Only child links of term links will be un-reset.
        $item['plid'] = $plid;
        $mlid = menu_link_save($item);
      }
      taxonomy_field_menu_update_term_path_alias($term, $taxonomy_field_menu);
    }
  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('taxonomy_field_menu', $e);
    throw $e;
  }
}

/**
 * Disable taxonomy field menu links.
 *
 * @param object $term
 *   Disable this term's menu link in taxonomy field menus.
 *
 * @param object $taxonomy_field_menu
 *   Disable term's menu link for this taxonomy field menu.
 */
function _taxonomy_field_menu_disable_term_link($term, $taxonomy_field_menu) {
  $path = 'taxonomy/term/' . $term->tid;
  if ($taxonomy_field_menu->custom_page) {
    $path = 'taxonomy_field_menu/' . $taxonomy_field_menu->menu_name . '/' . $term->tid;
  }
  db_update('menu_links')
    ->fields(array('hidden' => 1))
    ->condition('menu_name', $taxonomy_field_menu->menu_name)
    ->condition('link_path', $path)
    ->execute();
}

/**
 * Enable taxonomy field menu links.
 *
 * @param object $term
 *   Enable this term's menu link in taxonomy field menus.
 *
 * @param object $taxonomy_field_menu
 *   Enable term's menu link for this taxonomy field menu.
 */
function _taxonomy_field_menu_enable_term_link($term, $taxonomy_field_menu) {
  $path = 'taxonomy/term/' . $term->tid;
  if ($taxonomy_field_menu->custom_page) {
    $path = 'taxonomy_field_menu/' . $taxonomy_field_menu->menu_name . '/' . $term->tid;
  }
  db_update('menu_links')
    ->fields(array('hidden' => 0))
    ->condition('menu_name', $taxonomy_field_menu->menu_name)
    ->condition('link_path', $path)
    ->execute();
}

/**
 * Delete one taxonomy field menu.
 *
 * @param object $taxonomy_field_menu
 *   This taxonomy field menu object we are processing.
 */
function _taxonomy_field_menu_delete_menu($taxonomy_field_menu) {
  $menu['menu_name'] = $taxonomy_field_menu->menu_name;
  // System-defined menus may not be deleted - only menus defined by this
  // module.
  $system_menus = menu_list_system_menus();
  if (isset($system_menus[$menu['menu_name']]) || !(db_query("SELECT 1 FROM {menu_custom} WHERE menu_name = :menu", array(':menu' => $menu['menu_name']))->fetchField())) {
    return;
  }

  // Reset all the menu links defined by the system via hook_menu().
  $result = db_query("SELECT * FROM {menu_links} ml INNER JOIN {menu_router} m ON ml.router_path = m.path WHERE ml.menu_name = :menu AND ml.module = 'system' ORDER BY m.number_parts ASC", array(':menu' => $menu['menu_name']), array('fetch' => PDO::FETCH_ASSOC));
  foreach ($result as $link) {
    menu_reset_item($link);
  }

  // Delete all links to the overview page for this menu.
  $result = db_query("SELECT mlid FROM {menu_links} ml WHERE ml.link_path = :link", array(':link' => 'admin/structure/menu/manage/' . $menu['menu_name']), array('fetch' => PDO::FETCH_ASSOC));
  foreach ($result as $link) {
    menu_link_delete($link['mlid']);
  }

  // We need to delete path alias for this taxonomy field menu, if this
  // taxonomy field menu has used custom term page.
  taxonomy_field_menu_delete_terms_path_alias($taxonomy_field_menu);

  menu_delete($menu);
  _taxonomy_field_menu_delete($menu);

}

/**
 * Get node(s) which has a tid value of term reference field.
 *
 * @param int $tid
 *   Term's tid. This is the term we need to get its direct associated nodes.
 *   To get term's child term nodes, see
 *   taxonomy_field_menu_get_term_all_nodes().
 *
 * @param string $field_name
 *   The taxonomy field with this term.
 *
 * @return array
 *   An array of nids. Or an emtpy array if no nid is found.
 *
 * @see taxonomy_field_menu_get_term_all_nodes()
 */
function _taxonomy_field_menu_get_term_field_nodes($tid, $field_name) {
  $nids = &drupal_static(__FUNCTION__, array());

  if (!isset($nids[$tid][$field_name])) {
    $field_table = 'field_data_' . $field_name;
    $query = db_select($field_table, 'f');
    // Only inlcude nodes published.
    $query->join('node', 'n', 'n.nid = f.entity_id');
    $query->condition('f.' . $field_name . '_tid', $tid);
    $query->condition('f.entity_type', 'node')
      ->condition('f.deleted', '0')
      ->condition('n.status', 1)
      ->fields('f', array('entity_id'));
    $nids[$tid][$field_name] = $query->execute()->fetchCol();
  }

  return $nids[$tid][$field_name];
}

/**
 * Get node title according to nid.
 *
 * This is a lightwieght function to get node title according to nid. The
 * popular way is to use node_load(), which will load the full node object
 * in memory, not necessary for our case.
 *
 * @param int $nid
 *   Node's nid.
 *
 * @return string
 *   Node's title.
 */
function _taxonomy_field_menu_get_node_title($nid) {
  $titles = &drupal_static(__FUNCTION__, array());
  if (!isset($titles[$nid])) {
    $query = db_select('node', 'n')
      ->fields('n', array('title'))
      ->condition('n.status', 1)
      ->condition('n.nid', $nid);
    $title = $query->execute()->fetchCol();
    $titles[$nid] = $title[0];
  }

  return $titles[$nid];
}

/**
 * Delete taxonomy field menu record from {taxonomy_field_menu}.
 *
 * @param array $menu
 *   This array contains only key -- 'menu_name'. Because menu_name is unique
 *   in table, we could use it to specificaly delete one taxonomy field menu
 *   entry.
 */
function _taxonomy_field_menu_delete($menu) {
  db_delete('taxonomy_field_menu')
    ->condition('menu_name', $menu['menu_name'])
    ->execute();
}

/**
 * Insert new taxonomy field menu to {taxonomy_field_menu}.
 *
 * @param object $taxonomy_field_menu
 *   This taxonomy_field_menu object we need to save into database.
 */
function _taxonomy_field_menu_insert_menu($taxonomy_field_menu) {
  db_insert('taxonomy_field_menu')
    ->fields(array(
        'field_name'  => $taxonomy_field_menu->field_name,
        'menu_name'   => $taxonomy_field_menu->menu_name,
        'vid'         => $taxonomy_field_menu->vid,
        'custom_page' => $taxonomy_field_menu->custom_page,
        'child_node'  => $taxonomy_field_menu->child_node,
        'sync_node'   => $taxonomy_field_menu->sync_node,
        'sync_term'   => $taxonomy_field_menu->sync_term,
        'node_type'   => $taxonomy_field_menu->node_type,
        'url_alias'   => $taxonomy_field_menu->url_alias,
      ))
    ->execute();
}

/**
 * Get taxonomy field menus from {taxonomy_field_menu}.
 *
 * It provides three parameters to get taxonomy field menu object(s).
 * According to the parameter order, once the previous parameter is provded,
 * next parameter(s) will be ignored. If no parameters are provided, it will
 * return an array of all taxonomy_field_menu in this site.
 *
 * As field_name and menu_name are unique keys inside {taxonomy_field_menu}
 * they will get one taxonomy_field_menu object, while vid could get multiple
 * taxonomy_field_menu assocaited.
 *
 * @param int $vid
 *   Vocabulary vid. One vocabulary could have many taxonomy field menus. If
 *   this parameter is provided, $field_name and $menu_name will be ignored.
 *
 * @param string $field_name
 *   Taxonomy field name. This parameter will be checked only when $vid is
 *   NULL. If this parameter is provided, $menu_name will be ignored.
 *
 * @param string $menu_name
 *   Taxonomy field menu's menu name. This parameter will be checked only when
 *   previous two parameters are NULL.
 *
 * @return object
 *   It will depend on the parameters to return one taxonomy_field_menu obejct
 *   (Null) or an array of taxonomy field menu objects(or empty array).
 */
function _taxonomy_field_menu_get_menus($vid = NULL, $field_name = NULL, $menu_name = NULL) {
  $menus = &drupal_static(__FUNCTION__);
  $vid_menus = &drupal_static(__FUNCTION__ . 'vid', array());
  $field_menu = &drupal_static(__FUNCTION__ . 'field', array());
  $menu_menu = &drupal_static(__FUNCTION__ . 'menu', array());

  $query = db_select('taxonomy_field_menu', 'tm')->fields('tm');

  if (empty($vid) && empty($field_name) && empty($menu_name)) {
    if (!isset($menus)) {
      $menus = $query->execute()->fetchAll();
    }
  }
  elseif (!empty($vid)) {
    if (!isset($vid_menus[$vid])) {
      $query->condition('tm.vid', $vid);
      $vid_menus[$vid] = $query->execute()->fetchAll();
    }
  }
  elseif (!empty($field_name)) {
    if (!isset($field_menu[$field_name])) {
      $query->condition('tm.field_name', $field_name);
      $field_menu[$field_name] = $query->execute()->fetchAll();
    }
  }
  elseif (!empty($menu_name)) {
    if (!isset($menu_menu[$menu_name])) {
      $query->condition('tm.menu_name', $menu_name);
      $menu_menu[$menu_name] = $query->execute()->fetchAll();
    }
  }

  if (empty($vid) && empty($field_name) && empty($menu_name)) {
    return $menus;
  }
  elseif (!empty($vid)) {
    return $vid_menus[$vid];
  }
  elseif (!empty($field_name)) {
    return reset($field_menu[$field_name]);
  }
  elseif (!empty($menu_name)) {
    return reset($menu_menu[$menu_name]);
  }

}

/**
 * Get term's mlid from {menu_links} with specific taxonomy field menu.
 *
 * @param int $tid
 *   Term's tid.
 *
 * @param object $taxonomy_field_menu
 *   taxonomy field menu object associated with this term.
 */
function _taxonomy_field_menu_get_term_mlid($tid, $taxonomy_field_menu) {
  $mlids = &drupal_static(__FUNCTION__, array());
  if (!isset($mlids[$taxonomy_field_menu->menu_name][$tid])) {
    $query = db_select('menu_links', 'ml');
    $query->condition('ml.menu_name', $taxonomy_field_menu->menu_name)
      ->fields('ml', array('mlid'));

    // Add link path and router path check according to custom_page config.
    if ($taxonomy_field_menu->custom_page) {
      $query->condition('ml.link_path', 'taxonomy_field_menu/' . $taxonomy_field_menu->menu_name . '/' . $tid)
        ->condition('ml.router_path', 'taxonomy_field_menu/%/%');
    }
    else {
      $query->condition('ml.link_path', 'taxonomy/term/' . $tid)
        ->condition('ml.router_path', 'taxonomy/term/%');
    }
    $result = $query->execute()->fetchField();
    $mlids[$taxonomy_field_menu->menu_name][$tid] = $result;
  }
  return $mlids[$taxonomy_field_menu->menu_name][$tid];
}

/**
 * Update a taxonomy field menu into database.
 *
 * @param object $taxonomy_field_menu
 *   taxonomy field menu object we are updating.
 */
function _taxonomy_field_menu_update_taxonomy_field_menu($taxonomy_field_menu) {
  db_update('taxonomy_field_menu')
    ->condition('field_name', $taxonomy_field_menu->field_name)
    ->fields(array(
      'node_type' => $taxonomy_field_menu->node_type,
      'child_node' => $taxonomy_field_menu->child_node))
    ->execute();
}
